# Generated by Django 3.2.15 on 2022-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=20)),
                ('description', models.TextField(help_text='Описание', max_length=200)),
                ('price', models.FloatField(help_text='Цена', max_length=5)),
            ],
        ),
    ]
