# Generated by Django 3.2.15 on 2022-09-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypage', '0002_auto_20220913_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Цена за услугу в КОПЕЙКАХ', max_length=50, verbose_name='Цена'),
        ),
    ]
