# Generated by Django 3.2.15 on 2022-09-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypage', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Цена за услугу в КОПЕЙКАХ', verbose_name='Цена'),
        ),
    ]
